[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "patchlib"
authors = [{name = "BretteFromNesUniverse", discord = "https://www.discord.gg/3DYCru4dCV"}]
dynamic = ["version", "description"]
